apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "backend-shivam-ingress"
  namespace: "kubernetes-cluster-shivam"
spec:
  tls:
    - secretName: tls-secret
  defaultBackend:
    service:
      name: "backend-shivam"
      port:
        number: 5000
